name: Deploy Docker Image to Artifact Registry

on:
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  
      contents: read   

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/211378719386/locations/global/workloadIdentityPools/github-actions/providers/github"
          service_account: "github-building-docker@thunderstorm-development.iam.gserviceaccount.com"

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-east4-docker.pkg.dev

      - name: Disable Docker BuildKit
        run: |
          echo "DOCKER_BUILDKIT=0" >> $GITHUB_ENV
          echo "DOCKER_CLI_EXPERIMENTAL=disabled" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t us-east4-docker.pkg.dev/thunderstorm-development/demo-push-repo1/dummy-image-wfi:latest .
        env:
          DOCKER_BUILDKIT: 0

      - name: Push Docker Image
        run: |
          docker push us-east4-docker.pkg.dev/thunderstorm-development/demo-push-repo1/dummy-image-wfi:latest

