name: Deploy Docker Image to Artifact Registry

on:
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  
      contents: read   

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: "access_token"
          workload_identity_provider: ""
          service_account: ""

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Disable Docker BuildKit
        run: |
          echo "DOCKER_BUILDKIT=0" >> $GITHUB_ENV
          echo "DOCKER_CLI_EXPERIMENTAL=disabled" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t 
        env:
          DOCKER_BUILDKIT: 0

      - name: Push Docker Image
        run: |
          docker push 

