name: Deploy Docker Image to Artifact Registry

on:
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'  

      - name: Configure Docker Authentication
        run: |
          gcloud auth configure-docker us-east4-docker.pkg.dev

      - name: Set Docker to classic builder
        run: |
          echo "DOCKER_CLI_EXPERIMENTAL=disabled" >> $GITHUB_ENV
          echo "DOCKER_BUILDKIT=0" >> $GITHUB_ENV


      - name: Build Docker Image
        run: |
          docker build -t us-east4-docker.pkg.dev/thunderstorm-development/demo-push-repo1/dummy-image:latest .
        env:
          DOCKER_BUILDKIT: 0

      - name: Push Docker Image
        run: |
          docker push us-east4-docker.pkg.dev/thunderstorm-development/demo-push-repo1/dummy-image:latest

